apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090  ***REMOVED*** Docker service name (bridge networking, internal port)
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 10s
      queryTimeout: 60s
      httpMethod: POST
