// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadNetwork returns the embedded CollectionSpec for network.
func loadNetwork() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetworkBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load network: %w", err)
	}

	return spec, err
}

// loadNetworkObjects loads network and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*networkObjects
//	*networkPrograms
//	*networkMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNetworkObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadNetwork()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// networkSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type networkSpecs struct {
	networkProgramSpecs
	networkMapSpecs
	networkVariableSpecs
}

// networkProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type networkProgramSpecs struct {
	TraceAccept         *ebpf.ProgramSpec `ebpf:"trace_accept"`
	TraceTcpClose       *ebpf.ProgramSpec `ebpf:"trace_tcp_close"`
	TraceTcpConnect     *ebpf.ProgramSpec `ebpf:"trace_tcp_connect"`
	TraceTcpRecvmsg     *ebpf.ProgramSpec `ebpf:"trace_tcp_recvmsg"`
	TraceTcpRecvmsgRet  *ebpf.ProgramSpec `ebpf:"trace_tcp_recvmsg_ret"`
	TraceTcpSendmsg     *ebpf.ProgramSpec `ebpf:"trace_tcp_sendmsg"`
	TraceUdpDestroySock *ebpf.ProgramSpec `ebpf:"trace_udp_destroy_sock"`
	TraceUdpRecvmsg     *ebpf.ProgramSpec `ebpf:"trace_udp_recvmsg"`
	TraceUdpRecvmsgRet  *ebpf.ProgramSpec `ebpf:"trace_udp_recvmsg_ret"`
	TraceUdpSendmsg     *ebpf.ProgramSpec `ebpf:"trace_udp_sendmsg"`
}

// networkMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type networkMapSpecs struct {
	ConnectionFlows *ebpf.MapSpec `ebpf:"connection_flows"`
	FilterModeMap   *ebpf.MapSpec `ebpf:"filter_mode_map"`
	HostNetnsMap    *ebpf.MapSpec `ebpf:"host_netns_map"`
	OffsetConfig    *ebpf.MapSpec `ebpf:"offset_config"`
	OverflowFlows   *ebpf.MapSpec `ebpf:"overflow_flows"`
	TempStorageMap  *ebpf.MapSpec `ebpf:"temp_storage_map"`
}

// networkVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type networkVariableSpecs struct {
}

// networkObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type networkObjects struct {
	networkPrograms
	networkMaps
	networkVariables
}

func (o *networkObjects) Close() error {
	return _NetworkClose(
		&o.networkPrograms,
		&o.networkMaps,
	)
}

// networkMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type networkMaps struct {
	ConnectionFlows *ebpf.Map `ebpf:"connection_flows"`
	FilterModeMap   *ebpf.Map `ebpf:"filter_mode_map"`
	HostNetnsMap    *ebpf.Map `ebpf:"host_netns_map"`
	OffsetConfig    *ebpf.Map `ebpf:"offset_config"`
	OverflowFlows   *ebpf.Map `ebpf:"overflow_flows"`
	TempStorageMap  *ebpf.Map `ebpf:"temp_storage_map"`
}

func (m *networkMaps) Close() error {
	return _NetworkClose(
		m.ConnectionFlows,
		m.FilterModeMap,
		m.HostNetnsMap,
		m.OffsetConfig,
		m.OverflowFlows,
		m.TempStorageMap,
	)
}

// networkVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type networkVariables struct {
}

// networkPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type networkPrograms struct {
	TraceAccept         *ebpf.Program `ebpf:"trace_accept"`
	TraceTcpClose       *ebpf.Program `ebpf:"trace_tcp_close"`
	TraceTcpConnect     *ebpf.Program `ebpf:"trace_tcp_connect"`
	TraceTcpRecvmsg     *ebpf.Program `ebpf:"trace_tcp_recvmsg"`
	TraceTcpRecvmsgRet  *ebpf.Program `ebpf:"trace_tcp_recvmsg_ret"`
	TraceTcpSendmsg     *ebpf.Program `ebpf:"trace_tcp_sendmsg"`
	TraceUdpDestroySock *ebpf.Program `ebpf:"trace_udp_destroy_sock"`
	TraceUdpRecvmsg     *ebpf.Program `ebpf:"trace_udp_recvmsg"`
	TraceUdpRecvmsgRet  *ebpf.Program `ebpf:"trace_udp_recvmsg_ret"`
	TraceUdpSendmsg     *ebpf.Program `ebpf:"trace_udp_sendmsg"`
}

func (p *networkPrograms) Close() error {
	return _NetworkClose(
		p.TraceAccept,
		p.TraceTcpClose,
		p.TraceTcpConnect,
		p.TraceTcpRecvmsg,
		p.TraceTcpRecvmsgRet,
		p.TraceTcpSendmsg,
		p.TraceUdpDestroySock,
		p.TraceUdpRecvmsg,
		p.TraceUdpRecvmsgRet,
		p.TraceUdpSendmsg,
	)
}

func _NetworkClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed network_arm64_bpfel.o
var _NetworkBytes []byte
